/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inter_presence;

/**
 *
 * @author leonardo
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Servicos = new javax.swing.JButton();
        jLabel_Bem_vindo = new javax.swing.JLabel();
        jLabel_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_Servicos.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        jButton_Servicos.setText("ENTRAR");
        jButton_Servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ServicosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Servicos);
        jButton_Servicos.setBounds(520, 340, 230, 40);

        jLabel_Bem_vindo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Bem_vindo.setForeground(new java.awt.Color(238, 238, 238));
        jLabel_Bem_vindo.setText("    SEJA BEM-VINDO AO \" I PRESENCE\"");
        getContentPane().add(jLabel_Bem_vindo);
        jLabel_Bem_vindo.setBounds(360, 210, 540, 80);

        jLabel_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_presence/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel_Fundo);
        jLabel_Fundo.setBounds(0, 0, 1310, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ServicosActionPerformed
        Login_Servicos tela = new Login_Servicos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Servicos;
    private javax.swing.JLabel jLabel_Bem_vindo;
    private javax.swing.JLabel jLabel_Fundo;
    // End of variables declaration//GEN-END:variables
}
