/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inter_presence;

import javax.swing.JOptionPane;

/**
 *
 * @author leonardo
 */
public class Login_Servicos extends javax.swing.JFrame {

    /**
     * Creates new form Login_Servicos
     */
    public Login_Servicos() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Fundo = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        imagem_login = new javax.swing.JLabel();
        jButton_ENTRAR = new javax.swing.JButton();
        jButton_VOLTAR = new javax.swing.JButton();
        UTilizador = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jComboBox_username = new javax.swing.JComboBox<>();
        jLabel_Fundo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(500, 340, 320, 40);

        imagem_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_presence/imagens/login2.png"))); // NOI18N
        getContentPane().add(imagem_login);
        imagem_login.setBounds(590, 110, 120, 140);

        jButton_ENTRAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ENTRAR.setText("ENTRAR");
        jButton_ENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ENTRAR);
        jButton_ENTRAR.setBounds(520, 420, 100, 40);

        jButton_VOLTAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_VOLTAR.setText("VOLTAR");
        jButton_VOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VOLTARActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_VOLTAR);
        jButton_VOLTAR.setBounds(690, 420, 100, 40);

        UTilizador.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        UTilizador.setForeground(new java.awt.Color(232, 232, 232));
        UTilizador.setText("User Name:");
        getContentPane().add(UTilizador);
        UTilizador.setBounds(370, 280, 120, 40);

        password.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(232, 232, 232));
        password.setText("Password:");
        getContentPane().add(password);
        password.setBounds(380, 340, 110, 40);

        jComboBox_username.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honácio Dias", "Kleivy Gomes" }));
        jComboBox_username.setAutoscrolls(true);
        jComboBox_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_username);
        jComboBox_username.setBounds(500, 284, 320, 40);

        jLabel_Fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_presence/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel_Fundo1);
        jLabel_Fundo1.setBounds(0, 0, 1320, 870);

        setSize(new java.awt.Dimension(1337, 989));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton_ENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ENTRARActionPerformed
         if (jComboBox_username.getSelectedItem().equals("Honácio Dias")&& jPasswordField1.getText().equals("1234")){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
         }else if(jComboBox_username.getSelectedItem().equals("Kleivy Gomes") && jPasswordField1.getText().equals("12345")){
            TelaPrincipal2 tela = new TelaPrincipal2();
            tela.setVisible(true);    
        }else {
            JOptionPane.showMessageDialog(rootPane, "Password inválido! Tente novamente.");
              }
    }//GEN-LAST:event_jButton_ENTRARActionPerformed

    private void jButton_VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VOLTARActionPerformed
            inicio tela = new inicio();
            tela.setVisible(true);
            dispose();     
    }//GEN-LAST:event_jButton_VOLTARActionPerformed

    private void jComboBox_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_usernameActionPerformed
      
    }//GEN-LAST:event_jComboBox_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Servicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UTilizador;
    private javax.swing.JLabel imagem_login;
    private javax.swing.JButton jButton_ENTRAR;
    private javax.swing.JButton jButton_VOLTAR;
    private javax.swing.JComboBox<String> jComboBox_username;
    private javax.swing.JLabel jLabel_Fundo;
    private javax.swing.JLabel jLabel_Fundo1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
