/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inter_presence;

/**
 *
 * @author leonardo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    public TelaPrincipal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_IPRESENCE = new javax.swing.JLabel();
        jLabel_FundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Formulario_Aluno = new javax.swing.JMenu();
        jMenuItem1_Adicionar_aluno = new javax.swing.JMenuItem();
        jMenu_Ferramentas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu_Sair = new javax.swing.JMenu();
        jMenuItem_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel_IPRESENCE.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel_IPRESENCE.setForeground(new java.awt.Color(238, 238, 238));
        jLabel_IPRESENCE.setText("SISTEMA DE MARCAÇÃO DE FALTAS");
        getContentPane().add(jLabel_IPRESENCE);
        jLabel_IPRESENCE.setBounds(340, 290, 680, 80);

        jLabel_FundoPrincipal.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_FundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_presence/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel_FundoPrincipal);
        jLabel_FundoPrincipal.setBounds(0, 0, 1340, 850);

        jMenu_Formulario_Aluno.setText("Marcar  Presença dos alunos");

        jMenuItem1_Adicionar_aluno.setText("Entrar");
        jMenuItem1_Adicionar_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_Adicionar_alunoActionPerformed(evt);
            }
        });
        jMenu_Formulario_Aluno.add(jMenuItem1_Adicionar_aluno);

        jMenuBar1.add(jMenu_Formulario_Aluno);

        jMenu_Ferramentas.setText("  Ferramentas");
        jMenuBar1.add(jMenu_Ferramentas);

        jMenu1.setText("    Informações");
        jMenuBar1.add(jMenu1);

        jMenu_Sair.setText("     Sair");

        jMenuItem_Sair.setText("Sair");
        jMenuItem_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SairActionPerformed(evt);
            }
        });
        jMenu_Sair.add(jMenuItem_Sair);

        jMenuBar1.add(jMenu_Sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1348, 921));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem_SairActionPerformed

    private void jMenuItem1_Adicionar_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_Adicionar_alunoActionPerformed
       Marcar_Presença tela = new Marcar_Presença();
       tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1_Adicionar_alunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_FundoPrincipal;
    private javax.swing.JLabel jLabel_IPRESENCE;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_Adicionar_aluno;
    private javax.swing.JMenuItem jMenuItem_Sair;
    private javax.swing.JMenu jMenu_Ferramentas;
    private javax.swing.JMenu jMenu_Formulario_Aluno;
    private javax.swing.JMenu jMenu_Sair;
    // End of variables declaration//GEN-END:variables
}
